<a href="https://colab.research.google.com/github/baebsae3123/BDA/blob/main/6%EC%A3%BC%EC%B0%A8_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 이미지 파일 보기

In [ ]:
from IPython.display import Image

image_path = '/content/화면 캡처 2026-04-08 140531.png'
display(Image(filename=image_path))

In [ ]:
import pandas as pd

df = pd.DataFrame([
    {'국어': 70, '수학': 89, '영어': 90},
    {'국어': 80, '영어': 99},
    {'수학': 66, '영어': 78}
])

df

     국어    수학  영어
0  70.0  89.0  90
1  80.0   NaN  99
2   NaN  66.0  78

In [ ]:
s1 = pd.Series([90, 80, 60, 66])
s2 = pd.Series([45, 73, 83, 99])
s3 = pd.Series([92, 75, 82, 75])

s1

0    90
1    80
2    60
3    66
dtype: int64

In [ ]:
df = pd.DataFrame({'국어': s1, '영어': s2, '수학': s3})
df

   국어  영어  수학
0  90  45  92
1  80  73  75
2  60  83  82
3  66  99  75

In [ ]:
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
fees = pd.Series([250000, 300000, 200000], name='fees')

df = pd.DataFrame([courses, fees])
df

              0        1       2
courses   Spark  PySpark  Hadoop
fees     250000   300000  200000

In [ ]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
df[courses.name] = courses
df

   courses
0    Spark
1  PySpark
2   Hadoop

In [ ]:
fees = pd.Series([250000, 300000, 200000], name='fees')
df[fees.name] = fees
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [ ]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [ ]:
df.dtypes

col1    int64
col2    int64
dtype: object

In [ ]:
dates = pd.date_range("20250101", periods=6)
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
dates[0]

Timestamp('2025-01-01 00:00:00')

In [ ]:
dates = pd.date_range("20250101", end="20250110")
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [8]:
import pandas as pd

dates = pd.date_range("20250101",periods=6, freq="D")
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

In [13]:
dates= pd.date_range("20250101",periods=6,freq="W")
dates

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09'],
              dtype='datetime64[ns]', freq='W-SUN')

In [9]:
# 1. 3일 간격으로 생성
dates = pd.date_range("20250101", periods=6, freq='3D')
dates

DatetimeIndex(['2025-01-01', '2025-01-04', '2025-01-07', '2025-01-10',
               '2025-01-13', '2025-01-16'],
              dtype='datetime64[ns]', freq='3D')

In [ ]:
# 2. 3시간 간격으로 생성
dates = pd.date_range("20250101", periods=6, freq='3H')
dates

/tmp/ipykernel_10928/3814922138.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range("20250101", periods=6, freq='3H')

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 03:00:00',
               '2025-01-01 06:00:00', '2025-01-01 09:00:00',
               '2025-01-01 12:00:00', '2025-01-01 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

In [ ]:
# 3. 주 단위(일요일 시작)로 생성
dates = pd.date_range("20250101", periods=6, freq='W')
dates

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09'],
              dtype='datetime64[ns]', freq='W-SUN')

In [ ]:
# 4. 명시적인 W-SUN 인자 사용 (2026년 기준)
dates = pd.date_range("20260101", periods=6, freq='W-SUN')
dates

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08'],
              dtype='datetime64[ns]', freq='W-SUN')

In [ ]:
# 1. 매주 화요일 기준 생성
dates = pd.date_range("20260101", periods=6, freq='W-TUE')
dates

DatetimeIndex(['2026-01-06', '2026-01-13', '2026-01-20', '2026-01-27',
               '2026-02-03', '2026-02-10'],
              dtype='datetime64[ns]', freq='W-TUE')

In [ ]:
# 2. 매주 금요일 기준 생성
dates = pd.date_range("20260101", periods=6, freq='W-FRI')
dates

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06'],
              dtype='datetime64[ns]', freq='W-FRI')

In [ ]:
# 3. 월말 기준 생성 (M 사용 시)
dates = pd.date_range("20250101", periods=6, freq='M')
dates

/tmp/ipykernel_10928/2640731242.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250101", periods=6, freq='M')

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
# 4. 월초 기준 생성 (MS 사용)
dates = pd.date_range("20250101", periods=6, freq='MS')
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [ ]:
# 1. 날짜 인덱스 생성
dates = pd.date_range("20250302", periods=6)
dates

DatetimeIndex(['2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05',
               '2025-03-06', '2025-03-07'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
import numpy as np
# 2. 데이터를 포함한 데이터프레임 생성
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-03-02 -0.306085 -1.214361 -0.175165 -0.432344
2025-03-03  1.210886 -1.631846 -1.240807 -0.150041
2025-03-04 -0.181286 -2.840883 -0.036137 -0.196761
2025-03-05 -0.941933 -0.185956  0.705581  0.664341
2025-03-06  0.980145 -2.191753 -0.200118  0.482729
2025-03-07  1.912531 -1.997261  1.992654 -0.605594

In [18]:
import pandas as pd
import numpy as np

# 1. 다양한 자료형을 가진 데이터프레임 생성
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20260302"),
    "C": pd.Series(np.arange(1, 3, .5)),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})

df2

     A          B    C  D      E    F
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

In [19]:
# 2. 각 열의 데이터 타입 확인
df2.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

In [20]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [21]:
pf['중간'] > 20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [22]:
pf[pf['중간'] > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [24]:
pf[pf['출석'] >= 19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [26]:
pf[(pf['기말'] >= 20 )& (pf['출석'] >= 19)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [27]:
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [28]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [29]:
pf.loc[['홍소희', '윤일형']]

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

In [30]:
pf.loc['윤일형':'유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [58]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [59]:
pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [61]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [60]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [31]:
pf.loc[pf.중간 > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [32]:
pf.loc[(pf.중간 > 10) & (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [34]:
# 1) 첫 번째 행 검색 (결과: Series)
pf.loc[pf.index[0]]  # # 첫 번째 행 검색

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [35]:
pf.loc[[pf.index[0]]]  # # 첫 번째 행 검색

     중간  기말  과제  출석
윤일형  25  35   8  18

In [36]:
pf.loc[pf.index[1:4]]  # # 슬라이싱 행 검색

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [37]:
pf.loc[pf.index[1:4]][['기말', '과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [38]:
pf.loc[:, '과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [39]:
pf.loc[:, '중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [40]:
pf.loc[:, ['기말', '출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

In [41]:
pf.loc[:, pf.columns[0]]

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [42]:
pf.loc[:, [pf.columns[0]]]

     중간
윤일형  25
강수희  18
홍소희  17
유한빈  12
신수빈  22

In [43]:
pf.loc[:, pf.columns[1:]]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [44]:
pf.loc[:, pf.columns[1:3]]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [45]:
pf.loc[:, pf.columns[1:]][['기말', '과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [46]:
pf.loc['윤일형', '출석']

np.int64(18)

In [47]:
pf.loc['윤일형':'유한빈', '기말']

윤일형    35
강수희    27
홍소희    17
유한빈    22
Name: 기말, dtype: int64

In [48]:
pf.loc['윤일형':'유한빈', '기말':'과제']

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9

In [49]:
pf.loc[pf.index[0], pf.columns[1]]

np.int64(35)

In [50]:
pf.loc[pf.index[0:3], pf.columns[2]]

윤일형     8
강수희    10
홍소희    10
Name: 과제, dtype: int64

In [51]:
pf.loc[pf.index[0:3], pf.columns[2:]]

     과제  출석
윤일형   8  18
강수희  10  20
홍소희  10  19

In [52]:
pf.iloc[1, 1]

np.int64(27)

In [53]:
pf.iloc[1:3, 1:]

     기말  과제  출석
강수희  27  10  20
홍소희  17  10  19

In [54]:
pf.iloc[:, 1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [55]:
pf.iloc[[1, 3, 4], 1:]

     기말  과제  출석
강수희  27  10  20
유한빈  22   9  20
신수빈  34   8  16

In [56]:
pf.iloc[[1, 3, 4], [0, 1]]

     중간  기말
강수희  18  27
유한빈  12  22
신수빈  22  34

In [69]:
import pandas as pd

df = pd.read_csv('2016년졸음운전.csv',
                 encoding='euc-kr',index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [70]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [72]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [73]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [74]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [75]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [76]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [77]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [78]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [81]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [80]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [88]:
display_side_by_side(df,df.mean(axis=1).to_frame())

NameError: name 'display_side_by_side' is not defined

In [94]:
# 1. 원본 데이터 복사
df2 = df.copy()

# 2. 새로운 열('재해자수') 추가
# '사망(명)'과 '부상(명)' 열을 가로 방향(axis=1)으로 더함
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [96]:
# 3. 각 열의 합계 계산 (기본값 axis=0, 세로 합계)
df2.sum()

# 4. 새로운 행('총계') 추가
# 데이터프레임의 모든 열에 대해 세로 방향(axis=0) 합계를 구해 '총계'라는 이름의 행으로 저장
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         4866    196   9798  9994

In [97]:
df2 > 10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [98]:
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         4866  196.0   9798  9994

In [99]:
df2[[True]*6 + [False]*7]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

In [100]:
df2['재해자수'] > 400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [111]:
 df[df['사망(명)'].isin([7, 10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [113]:
 df[(df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350)]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [114]:
 df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [101]:
df2[df2['재해자수'] > 400]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         4866    196   9798  9994

In [102]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [103]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [118]:
# 다양한 range를 활용한 생성
df = pd.DataFrame({
    'A': range(1, 6),
    'B': range(6, -3, -2),
    'C': range(10, 5, -1),
    'D clmns': range(3, -2, -1),
    'E': ['python', 'java', 'python', 'go', 'python']
})

In [119]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [120]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [121]:
df.query('A==`D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [122]:
df.query('A=="D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [124]:
df[df.A == df["D clmns"]]

   A  B  C  D clmns     E
1  2  4  9        2  java

In [125]:
df.query('A > 3 | B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [126]:
df.query('A > 2 & C < 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [127]:
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python